### PR TITLE
Add proxy support

### PR DESCRIPTION
**Pull request by AlexandrePTJ**

### CODE REVIEW

**Comment by hechtus** [comment]
Thanks! Do you have an idea how to solve the Travis CI build error?

**Comment by AlexandrePTJ** [comment]
I think that you don't need to install mopidy==dev throut pip as it is
already installed from apt.

2014-02-17 9:52 GMT+01:00 Ronald Hecht notifications@github.com:

> Thanks! Do you have an idea how to solve the Travis CI build error?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/hechtus/mopidy-radio-de/pull/6#issuecomment-35238352
> .

## 

Cordialement,
Alexandre Petitjean.

**Comment by jodal** [comment]
The Travis CI error is caused by updated `pip` on their servers. In `.travis.yml`, change the `pip` line to:

```
pip install --allow-unverified=mopidy coveralls flake8 mopidy==dev python-dateutil
```

**Comment by jodal** [comment]
Yes, you do. The install from apt-get is only to get the non-pure-Python dependencies installed. The Mopidy install from the Debian package goes into /usr/share/mopidy, and won't be found by Python code installed by pip or run from Git repos without tweaking `PYTHONPATH`. We also want extensions to test against Mopidy's development branch, thus we install Mopidy both with apt-get and pip.

**Comment by hechtus** [comment]
@jodal Thanks for clarification. Just fixed it!

**Pull request merged**
